### ISSUE TITLE
multitoken?

### ISSUE THREAD

**Issue by tman10001** [scripted-1337/Discord-Mass-Mention#1]

**Comment by tman10001** [comment]
is it possible?

**Comment by scripted-1337** [comment]
yes it is possible
but ill do multi token support later

**Comment by tman10001** [comment]
oh ok, when do you possibly think youll be able to do it

**Comment by scripted-1337** [comment]
gna release it in the next 6/5 hours ig ;)

**Comment by tman10001** [comment]
oh okay thanks

**Comment by tman10001** [comment]
u still gonna post i?

**Comment by scripted-1337** [comment]
done
;)

**Comment by tman10001** [comment]
tysm
